   // #define audioInput "lav"
    #define SCENE1 "scena1"
    #define SCENE2 "scena2"
    #define SCENE3 "scena3"
    #define SCENE4 "scena4"
    #define SCENE5 "scena5"
    #define SCENE6 "scena6"

    #define SOURCE_SCENE "source key"
    #define SOURCE_KEY1 "source key1"
    #define SOURCE_KEY2 "source key2"
    #define SOURCE_KEY3 "source key3"
    #define SOURCE_KEY4 "source key4"
    #define SOURCE_KEY5 "source key5"
    #define SOURCE_KEY6 "source key6"
   