   // #define audioInput "lav"
    #define SCENE1 "mix1"
    #define SCENE2 "Scena 2"
    #define SCENE3 "Scena 3"
    #define SCENE4 "arduino"
    #define SCENE5 "zoom2"
    #define SCENE6 "telescopio"

    #define SOURCE_SCENE "mix1"
    #define SOURCE_KEY1 "Scena 3"
    #define SOURCE_KEY2 "Scena 2"
    #define SOURCE_KEY3 "schermo"
    #define SOURCE_KEY4 "ardu"
    #define SOURCE_KEY5 "telescopio"
    #define SOURCE_KEY6 "zoom2"
   